version: '3'
services:
  db:
    container_name: "actifio-oracle"
    volumes:
      - type: "bind"
        source: "/act"
        target: "/act"
        bind-propagation: "shared"
    environment:
      ACT_APPLIANCE: "mysky"
      ACT_USER: "demo"
      ACT_PASS: "demo"
      ACT_SRCHOST: "ora-master-server"
      ORACLE_HOST: "masivedb"
      ORACLE_HOME: "/opt/oracle/app/product/11204/ora_1"
    restart: "never"
    ports:
      - "1521:1521"
    image: oracle11204
