version: '3.7'
services:
  db:
    environment:
################ Change Only Within This Block ################      
      ACT_APPLIANCE: "my-sky"
      ACT_USER: "demo"
      ACT_PASS: "demo"
      ACT_SRCHOST: "master-db-server"
      ACT_APPNAME: "masivedb"
      ORACLE_SID: "mycopy"
      ORACLE_HOME: "/opt/oracle/app/product/11204/ora_1"
    container_name: actifio-oracle
    image: "ora-actifio"
##################### End of Change Block #####################
    volumes:
      - type: bind
        source: /act
        target: /act
        bind:
          propagation: shared
    ports:
      - "1521:1521"

